from pydantic import BaseModel, Field
from typing import List, Optional
from backend.core.config import settings

class SearchRequest(BaseModel):
    query: str = Field(..., min_length=1, max_length=settings.MAX_QUERY_LENGTH, description="The search query string")
    limit: int = Field(default=10, ge=1, le=50, description="Max number of candidate URLs to retrieve")

class SearchResult(BaseModel):
    title: str = Field(..., description="The title of the search result")
    url: str = Field(..., description="The URL of the search result page")
    snippet: str = Field(..., description="A snippet summary of the page content")
    engine: str = Field(..., description="The search engine that discovered this URL")
    score: float = Field(default=0.0, description="Relevance rank score generated by the engine or ranker")

class SearchResponse(BaseModel):
    query: str = Field(..., description="The search query processed")
    total: int = Field(..., description="Total number of results returned")
    results: List[SearchResult] = Field(default=[], description="The list of normalized search results")
