"""add_phase7_tables

Revision ID: 9da53dfa082d
Revises: a80db2e1a45f
Create Date: 2026-07-22 17:27:44.022695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da53dfa082d'
down_revision: Union[str, Sequence[str], None] = 'a80db2e1a45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('research_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_conversations_id'), 'research_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_research_conversations_research_id'), 'research_conversations', ['research_id'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_id'), 'research_notes', ['id'], unique=False)
    op.create_index(op.f('ix_research_notes_research_id'), 'research_notes', ['research_id'], unique=False)
    op.create_table('saved_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_sources_id'), 'saved_sources', ['id'], unique=False)
    op.create_index(op.f('ix_saved_sources_research_id'), 'saved_sources', ['research_id'], unique=False)
    op.create_table('workspace_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'research_id', name='uq_workspace_research')
    )
    op.create_index(op.f('ix_workspace_research_id'), 'workspace_research', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_research_research_id'), 'workspace_research', ['research_id'], unique=False)
    op.create_index(op.f('ix_workspace_research_workspace_id'), 'workspace_research', ['workspace_id'], unique=False)
    op.create_table('research_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['research_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_messages_conversation_id'), 'research_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_research_messages_id'), 'research_messages', ['id'], unique=False)
    op.create_table('message_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=200), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['research_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_evidence_id'), 'message_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_message_evidence_message_id'), 'message_evidence', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_evidence_message_id'), table_name='message_evidence')
    op.drop_index(op.f('ix_message_evidence_id'), table_name='message_evidence')
    op.drop_table('message_evidence')
    op.drop_index(op.f('ix_research_messages_id'), table_name='research_messages')
    op.drop_index(op.f('ix_research_messages_conversation_id'), table_name='research_messages')
    op.drop_table('research_messages')
    op.drop_index(op.f('ix_workspace_research_workspace_id'), table_name='workspace_research')
    op.drop_index(op.f('ix_workspace_research_research_id'), table_name='workspace_research')
    op.drop_index(op.f('ix_workspace_research_id'), table_name='workspace_research')
    op.drop_table('workspace_research')
    op.drop_index(op.f('ix_saved_sources_research_id'), table_name='saved_sources')
    op.drop_index(op.f('ix_saved_sources_id'), table_name='saved_sources')
    op.drop_table('saved_sources')
    op.drop_index(op.f('ix_research_notes_research_id'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_id'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_research_conversations_research_id'), table_name='research_conversations')
    op.drop_index(op.f('ix_research_conversations_id'), table_name='research_conversations')
    op.drop_table('research_conversations')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
