"""initial_schema

Revision ID: a80db2e1a45f
Revises: 
Create Date: 2026-07-22 16:48:47.630236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80db2e1a45f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.create_table('request_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('search_duration_ms', sa.Integer(), nullable=False),
    sa.Column('crawl_duration_ms', sa.Integer(), nullable=False),
    sa.Column('rag_duration_ms', sa.Integer(), nullable=False),
    sa.Column('generation_duration_ms', sa.Integer(), nullable=False),
    sa.Column('sources_analyzed', sa.Integer(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_metrics_created_at'), 'request_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_metrics_id'), 'request_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_request_metrics_request_id'), 'request_metrics', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_metrics_research_id'), 'request_metrics', ['research_id'], unique=False)
    op.create_index(op.f('ix_crawl_results_crawled_at'), 'crawl_results', ['crawled_at'], unique=False)
    op.create_index(op.f('ix_crawl_results_search_id'), 'crawl_results', ['search_id'], unique=False)
    op.create_index(op.f('ix_generated_answers_created_at'), 'generated_answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_answers_search_id'), 'generated_answers', ['search_id'], unique=False)
    op.create_index(op.f('ix_research_contradictions_research_id'), 'research_contradictions', ['research_id'], unique=False)
    op.create_index(op.f('ix_research_sessions_started_at'), 'research_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_research_sources_research_id'), 'research_sources', ['research_id'], unique=False)
    op.create_index(op.f('ix_research_subqueries_research_id'), 'research_subqueries', ['research_id'], unique=False)
    op.create_index(op.f('ix_search_queries_created_at'), 'search_queries', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_queries_created_at'), table_name='search_queries')
    op.drop_index(op.f('ix_research_subqueries_research_id'), table_name='research_subqueries')
    op.drop_index(op.f('ix_research_sources_research_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sessions_started_at'), table_name='research_sessions')
    op.drop_index(op.f('ix_research_contradictions_research_id'), table_name='research_contradictions')
    op.drop_index(op.f('ix_generated_answers_search_id'), table_name='generated_answers')
    op.drop_index(op.f('ix_generated_answers_created_at'), table_name='generated_answers')
    op.drop_index(op.f('ix_crawl_results_search_id'), table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_crawled_at'), table_name='crawl_results')
    op.drop_index(op.f('ix_request_metrics_research_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_request_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_created_at'), table_name='request_metrics')
    op.drop_table('request_metrics')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
