"use client";

import React, { useRef, useEffect } from "react";
import { Evidence, Citation } from "../../types/evidence";
import { Source } from "../../types/source";
import { X, ExternalLink, ShieldCheck, HelpCircle } from "lucide-react";

interface EvidenceModalProps {
  citation: Citation;
  evidence: Evidence;
  source: Source;
  onClose: () => void;
}

export default function EvidenceModal({
  citation,
  evidence,
  source,
  onClose
}: EvidenceModalProps) {
  const modalRef = useRef<HTMLDivElement>(null);

  // Close modal on clicking outside
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (modalRef.current && !modalRef.current.contains(event.target as Node)) {
        onClose();
      }
    }

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [onClose]);

  // Disable body scroll when modal is open
  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = "unset";
    };
  }, []);

  return (
    <div className="fixed inset-0 bg-zinc-900/40 dark:bg-black/75 backdrop-blur-xs flex items-center justify-center p-4 z-50">
      <div
        ref={modalRef}
        className="w-full max-w-lg peec-card bg-white dark:bg-zinc-900 border border-zinc-200/90 dark:border-zinc-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150"
      >
        {/* Header */}
        <div className="p-4 border-b border-zinc-200/80 dark:border-zinc-800 flex items-center justify-between bg-zinc-50/50 dark:bg-zinc-900/50">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-zinc-900 dark:text-zinc-100" />
            <h3 className="text-sm font-bold text-zinc-900 dark:text-zinc-50">
              RAG Evidence Chunk [{citation.id}]
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 hover:bg-zinc-200/60 dark:hover:bg-zinc-800 rounded-lg text-zinc-500 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Source Reference */}
        <div className="p-4 border-b border-zinc-200/60 dark:border-zinc-800/60">
          <span className="text-[10px] font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-wider block">
            Grounded Source
          </span>
          <h4 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 mt-1">
            {source.title}
          </h4>
          <span className="text-xs text-zinc-500 dark:text-zinc-400 block mt-0.5 font-medium">
            Domain: {source.domain}
          </span>
        </div>

        {/* Evidence Content */}
        <div className="p-4 flex-1 overflow-y-auto">
          <span className="text-[10px] font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-wider block mb-2">
            Retrieved Context
          </span>
          <div className="p-3.5 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200/80 dark:border-zinc-800 rounded-xl text-xs text-zinc-800 dark:text-zinc-200 leading-relaxed font-mono italic">
            "{evidence.content}"
          </div>
        </div>

        {/* Footer Relevance Score & Link */}
        <div className="p-4 border-t border-zinc-200/80 dark:border-zinc-800 flex items-center justify-between bg-zinc-50/50 dark:bg-zinc-900/50">
          <div className="flex flex-col gap-1 w-1/2">
            <div className="flex items-center gap-1.5">
              <span className="text-[11px] font-semibold text-zinc-600 dark:text-zinc-400">
                Relevance Rank
              </span>
              <span title="Vector similarity match score generated by local model embeddings" className="cursor-help">
                <HelpCircle className="w-3.5 h-3.5 text-zinc-400" />
              </span>
            </div>
            
            <div className="flex items-center gap-2">
              {/* Progress bar */}
              <div className="w-full bg-zinc-200 dark:bg-zinc-800 rounded-full h-1.5 overflow-hidden">
                <div
                  className="bg-zinc-900 dark:bg-zinc-100 h-1.5 rounded-full"
                  style={{ width: `${evidence.relevanceScore}%` }}
                />
              </div>
              <span className="text-xs font-bold text-zinc-900 dark:text-zinc-100 whitespace-nowrap">
                {evidence.relevanceScore}%
              </span>
            </div>
          </div>

          <a
            href={source.url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 py-1.5 px-3.5 bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-100 dark:hover:bg-white text-white dark:text-zinc-900 rounded-xl font-bold text-xs transition-all shadow-xs"
          >
            <span>Open Original</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      </div>
    </div>
  );
}
